version: '3.8'
services:
  postgres_dev:
    image: postgres:15.6
    restart: always
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=coding_club
    volumes:
      - postgres-dev-data:/var/lib/postgresql/data
    ports:
      - '5434:5432'

volumes:
  postgres-dev-data: